### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by cacack** [LowPowerLab/RaspberryPi-Gateway#13]
It would be helpful if the "releases" were tagged in git.  This would allow users to clone the repository based on an exact set of files versus getting the latest.

**Comment by LowPowerLab** [comment]
Nice suggestion. I was not aware how to use this git feature.
I tagged an older commit (v8) and I created a v8.2 release at the latest commit.
I will start tagging and using releases.
Thanks for raising this up and sorry for the late response.
