### ISSUE TITLE
Add installer script

### ISSUE THREAD

**Issue by karrots** [LowPowerLab/RaspberryPi-Gateway#23]
Where should it be added to the root? Some installer directory with the unit file, rsyslog, and other similar configs??

**Comment by LowPowerLab** [comment]
Either along with other config files, or maybe it can be in the root.
If in root then could it delete itself when its done?

**Comment by LowPowerLab** [comment]
The more I think about this, it should probably go in the root dir, not under _piConfigs

**Comment by karrots** [comment]
One thing to remember about this script. The way it is written currently is that it doesn't assume its in the cloned repository. In fact, it works best to be run not in the repo. So one would download just this script then run it on a fresh Rasbian image on their RPi.

Deleting the script is an option but one that can have unforeseen issues. Example it might delete its self on a bad install. Probably better to tell folks to delete it manually.

**Comment by LowPowerLab** [comment]
Right, I was just debating about the location. Install is not really config. The _piConfigs is an old and not really great name for a directory either.

**Comment by LowPowerLab** [comment]
I think this is pretty much done, setup can be initiated like this, as shown in [the guide](https://lowpowerlab.com/guide/gateway/setup-software/):

```
cd /home/pi
sudo wget https://raw.githubusercontent.com/LowPowerLab/RaspberryPi-Gateway/master/.setup/gatewaysetup.sh
sudo bash gatewaysetup.sh && sudo rm gatewaysetup.sh
```
