### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by gigawatts** [LowPowerLab/RaspberryPi-Gateway#30]
Brand new Raspian jessie lite install (2017-03-02).

sudo apt-get update && sudo apt-get install npm git
after cloning this git repo and running "npm install", the following errors result:

```
 $ npm install

> RaspberryPi-Gateway@8.8.0 preinstall /home/pi/RaspberryPi-Gateway
>

npm WARN engine request@2.78.0: wanted: {"node":">= 4"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN engine form-data@2.1.4: wanted: {"node":">= 0.12"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine hawk@3.1.3: wanted: {"node":">=0.10.32"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.29","npm":"1.4.21"})
/
> serialport@2.0.7-beta5 install /home/pi/RaspberryPi-Gateway/node_modules/serialport
> node-pre-gyp install --fallback-to-build

/usr/bin/env: node: No such file or directory
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! serialport@2.0.7-beta5 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 127
npm ERR!
npm ERR! Failed at the serialport@2.0.7-beta5 install script.
npm ERR! This is most likely a problem with the serialport package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls serialport
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 4.4.50+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/pi/RaspberryPi-Gateway
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/RaspberryPi-Gateway/npm-debug.log
npm ERR! not ok code 0

```

**Comment by gigawatts** [comment]
Nevermind, I ran the script as described here:  https://lowpowerlab.com/guide/gateway/setup-software/

Everything installed correctly.

**Comment by gigawatts** [comment]
I take that back, the above install script ran correctly, but the gateway service will not start. Here is the error message when trying to start it manually:

root@pione:~# /bin/sh -c /usr/bin/node /home/pi/gateway/gateway.js
/home/pi/gateway/gateway.js: 1: /home/pi/gateway/gateway.js: /usr/bin/node: not found

**Comment by LowPowerLab** [comment]
Thanks, just got to see this.
Were you able to find a fix or alter the script for this?

**Comment by gigawatts** [comment]
Sort of, but it's still not running right. Turns out there's a conflict of
packages using the same binary name "node". There's a ham radio app name
node, and node from older nodejs.

Installing nodejs-legacy adds a symlink from node to nodejs, which at least
let's the node command in the startup script run, but it returns zero
output, and doesn't open any sockets for the webserver to connect to.

**Comment by LowPowerLab** [comment]
I just tried it on the latest raspbian-lite (4-10-2017) and it works just fine. No node conflicts with any packages. You need to use the bash setup script as per instructions.

**Comment by gigawatts** [comment]
I just re-flashed again, completely clean build using 2017-04-10-raspbian-jessie-lite.img, download the script per your instructions, it ran and installed successfully, but it results in the exact same error I had before when the gateway service tries to start.

```
pi@pione:~ $ sudo systemctl restart gateway.service
pi@pione:~ $ sudo systemctl status gateway.service
● gateway.service - Moteino Gateway Service
   Loaded: loaded (/etc/systemd/system/gateway.service; enabled)
   Active: failed (Result: start-limit) since Sat 2017-04-22 20:44:16 UTC; 3s ago
  Process: 1135 ExecStop=/bin/kill -s SIGTERM $MAINPID (code=exited, status=0/SUCCESS)
  Process: 1132 ExecStart=/bin/sh -c /usr/bin/node /home/pi/gateway/gateway.js >> /home/pi/gateway/logs/gateway.sys.log 2>&1 (code=exited, status=127)
 Main PID: 1132 (code=exited, status=127)

Apr 22 20:44:16 pione systemd[1]: gateway.service holdoff time over, scheduling restart.
Apr 22 20:44:16 pione systemd[1]: Stopping Moteino Gateway Service...
Apr 22 20:44:16 pione systemd[1]: Starting Moteino Gateway Service...
Apr 22 20:44:16 pione systemd[1]: gateway.service start request repeated too quickly, refusing to start.
Apr 22 20:44:16 pione systemd[1]: Failed to start Moteino Gateway Service.
Apr 22 20:44:16 pione systemd[1]: Unit gateway.service entered failed state.
pi@pione:~ $ tail /home/pi/gateway/logs/gateway.sys.log
/bin/sh: 1: /usr/bin/node: not found
/bin/sh: 1: /usr/bin/node: not found
/bin/sh: 1: /usr/bin/node: not found
/bin/sh: 1: /usr/bin/node: not found
/bin/sh: 1: /usr/bin/node: not found
/bin/sh: 1: /usr/bin/node: not found
/bin/sh: 1: /usr/bin/node: not found
/bin/sh: 1: /usr/bin/node: not found
/bin/sh: 1: /usr/bin/node: not found
/bin/sh: 1: /usr/bin/node: not found
```

**Comment by gigawatts** [comment]
Ok, I can confirm this image and script works flawlessly on a Pi 2. The above was done on a Pi 1. What can we do to make the script work regardless of Pi version?

**Comment by LowPowerLab** [comment]
I tried it and it works on a Pi3. Also on Pi2. I haven't tried Pi1 though.
My aim is to make it work with the latest Pi, too much work to keep it updated for all hardware revisions and all the changes in the distributions.
The node and packages versions are always subject to change. Whats hard there is that i cant just link the latest available node because some packages and dependencies fail. So all has to be carefully orchestrated and tested.
Please continue to update me on your findings. If you could summarize what fails on what Pi revision that would help. Thanks!

**Comment by karrots** [comment]
This issue is because for the RPi 1 there is no `.deb` to download so the install script downloads and manually installs the NodeJS binaries. Something is going wrong with this code path (its only hit on an RPi 1) and the binaries are not being installed correctly.

Try executing `sudo bash -x gatewaysetup.sh` on a fresh install and paste any errors that are shown.  The `-x` on the script will turn on debug mode.

**Comment by gigawatts** [comment]
Looking through the setup script a bit closer, there is an if statement for the NodeJS install specific to "armv6l" the CPU in both the Pi 1 and Pi Zero. 

I see the issue in that block of code. At line 56 of the setup script ( https://github.com/LowPowerLab/RaspberryPi-Gateway/blob/master/.setup/gatewaysetup.sh#L56 ) it is moving the contents of the extracted tar, a directory named `node-v4.6.2-linux-armv6l`, to `/opt/nodejs`, but then is making symlinks from `/opt/nodejs/bin/` instead of from the resulting `/opt/nodejs/node-v4.6.2-linux-armv6l/bin`.

The simplest way to fix this would be to modify line 56 to instead read:
` sudo mv node-v4.6.2-linux-armv6l/* $NODEDIR`

That way the underlying bin, include, lib, share directories end up in `/opt/nodejs/` where the rest of the script expects them to be.

I just tested this modification on a fresh flash of raspian, and it fixes the "node not found error", and the gateway starts up as expected.

**Comment by LowPowerLab** [comment]
@gigawatts thanks so much, i've just committed this change in the master.
Also thank you @karrots for helping!
