### ISSUE TITLE
Webkit Crashes on Humidity w/ WeatherShield R2

### ISSUE THREAD

**Issue by Gerrymandered** [LowPowerLab/RaspberryPi-Gateway#35]
## Issue
WebKit crashes when viewing Humidity graph on Weather node.

## Workarounds

1. Use a different browser. (i.e. Mozilla Firefox, Chrome)
2. Open Web Inspector (`⌘ + ⌥ + I`) and proceed to view page.

## Debug
**DEVICES USED:**  
iPhone 6 - iOS 11.3rc - Safari
MacBook Pro (Mid-2012) - macOS 10.13.4

Safari - _11.1 (13605.1.33.1.2)_  
Safari Technology Preview - _Release 52 (Safari 11.2, WebKit 13606.1.9.3.1)_
Firefox - _59.0.2 (64-bit)_
Chrome - _Version 65.0.3325.181 (Official Build) (64-bit)_

**GATEWAY:**
V. 8.10.0
MoteinoUSB-R6
RasperryPi 0w
OS: Raspbian 9.3 stretch
Kernel: armv6l Linux 4.9.80+

**AFFECTING NODE:**
Moteino-R6 / WeatherShield-R2

[Crash Report](https://github.com/LowPowerLab/RaspberryPi-Gateway/files/1866658/com.apple.WebKit.WebContent_2018-04-01-155836_MattBook.crash.zip)

**Comment by LowPowerLab** [comment]
Thanks Matthew, I think this must be the graph smoothing js causing the problem. Otherwise nothing is different from other graphs. I don't have a mac so please try to comment out the H metric in your [userMetrics/_example.js](https://github.com/LowPowerLab/RaspberryPi-Gateway/blob/master/userMetrics/_example.js) file and see if it still happens:

`H:
  {
    name: 'H',
    regexp: /\bH\:([\d\.]+)\b/i,
    value: '',
    duplicateInterval: 3600,
    unit: '%',
    pin: 1,
    graph: 1,
    graphOptions:
    {
      legendLbl: 'Humidity',
      lines:
      {
        lineWidth: 1
      },
      yaxis:
      {
        autoscaleMargin: 0.25
      },
      series:
      {
        curvedLines:
        {
          active: true,
          apply: true,
          //monotonicFit: true, //makes the curve tight to datapoints
          //nrSplinePoints: 5 //number of sample points (of the spline) in between two consecutive points (more = smoother)
        }
      }
    }`

**Comment by Gerrymandered** [comment]
It works now. I changed the `_example.js` to disable graph smoothing as you said. It was the graph smoothing as you said.

Thanks!

```js
H:
  {
    name: 'H',
    regexp: /\bH\:([\d\.]+)\b/i,
    value: '',
    duplicateInterval: 3600,
    unit: '%',
    pin: 1,
    graph: 1,
    graphOptions:
    {
      legendLbl: 'Humidity',
      lines:
      {
        lineWidth: 1
      },
      yaxis:
      {
        autoscaleMargin: 0.25
      },
      series:
      {
        curvedLines:
        {
          active: false,
          apply: false,
          //monotonicFit: true, //makes the curve tight to datapoints
          //nrSplinePoints: 5 //number of sample points (of the spline) in between two consecutive points (more = smoother)
        }
      }
    }
}
```
