### ISSUE TITLE
without moteino

### ISSUE THREAD

**Issue by shiva1234567** [LowPowerLab/RaspberryPi-Gateway#37]
Hello felix..!

very much impressed about your work in home automation gateway. thank you..!

So, is it possible to connect different nodes to gateway by hard wiring them to the raspberry pi and get that integration for controlling into the dashboard provided. in other words is moteino is mandatory to use for this implementation or we can still use this integration without moteino and control them using the same interface..or read the status of the sensors on the same web interface...., if yes how to do it ..? are you planning to record same vdo for the concern i asked..!

eagerly waiting for your comment on the issue..!
thank you..!

**Comment by LowPowerLab** [comment]
Duplicate. Please don't open more issues. I already answered the questions, more in the forum please.
Thanks
