### ISSUE TITLE
Send SMS to multiple recipients

### ISSUE THREAD

**Issue by Lcreager** [LowPowerLab/RaspberryPi-Gateway#39]
It would be nice to have the ability to send SMS alerts to multiple recipients.  See the PR for how I implemented this.

**Comment by LowPowerLab** [comment]
Great, but instead of this code change, can't we just add more comma separated emails in the "TO" field on the settings page?
Since SMS is ultimately achieved by email, it works for that as well as sending emails.

**Comment by Lcreager** [comment]
I guess I'm a little confused.  Which field would we enter the comma separated emails in on the settings page?

This code change allows that for the smsAlerrtsTo field, did I miss functionality somewhere?

This is what my settings page looks like after this change:

![image](https://user-images.githubusercontent.com/6296078/68303232-6e4bfe80-0071-11ea-8b54-ca2149370353.png)

Before, I could only have one email in the smsAlertsTo field

**Comment by LowPowerLab** [comment]
Both email/sms fields are email addresses. You can enter them as comma separated. Nodemailer will send 1 email to all those addresses. Like in your email if you type multiple recipients, comma separated.
You dont need to split by comma, and send an email for each address.
Making sense?

**Comment by Lcreager** [comment]
AH!  I guess I don't remember testing that.  For some reason I don't think it worked, but I may not be remembering correctly at all.  Let me try real quick.

**Comment by Lcreager** [comment]
Works just fine without the change.  I don't know why I thought it did not.
