### ISSUE TITLE
Convert configs to config npm module

### ISSUE THREAD

**Issue by karrots** [LowPowerLab/RaspberryPi-Gateway#7]
Felix, I have used the config npm module in the past to store configs similar to your settings.js One benifit to the module is it allows for a default config and a local config. Anything in the local config overrides things in the default config. This can make testing, & automated deployment a bit easier.

I was thinking of creating a PR to change up the settings.js to this module. One question I have is what format would you like the settings file to be in if such a conversion were to happen? 

It supports JSON, CSON, YAML, JS files, and many others.

https://github.com/lorenwest/node-config/wiki/Configuration-Files

**Comment by LowPowerLab** [comment]
Thanks for the suggestion, I guess in my impromptu config variant I used the "JSON5" style notation.

**Comment by karrots** [comment]
Ok I have a branch based off of the branch PR #6 is based on. So if you compare to your master it will show the commits in PR #6 as well. 

https://github.com/karrots/RaspberryPi-Gateway/tree/config-gateway

**Comment by karrots** [comment]
Closing this as nconf was used instead.
